variable "project_name" {
  description = "Lowercase project identifier used in resource names."
  type        = string
  default     = "media-platform"

  validation {
    condition     = can(regex("^[a-z0-9][a-z0-9-]{1,18}[a-z0-9]$", var.project_name))
    error_message = "project_name must be 3-20 lowercase alphanumeric or hyphen characters and cannot start or end with a hyphen."
  }
}

variable "environment" {
  description = "Deployment environment identifier, such as dev, staging, or prod."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9][a-z0-9-]{0,8}[a-z0-9]$", var.environment))
    error_message = "environment must be 2-10 lowercase alphanumeric or hyphen characters and cannot start or end with a hyphen."
  }
}

variable "permissions_boundary_arn" {
  description = "IAM permissions boundary policy ARN"
  type        = string
  default     = null
}

variable "ingest_prefix" {
  description = "S3 object-key prefix monitored for new source videos."
  type        = string
  default     = "incoming/"

  validation {
    condition     = length(var.ingest_prefix) > 0 && endswith(var.ingest_prefix, "/")
    error_message = "ingest_prefix must be non-empty and end with '/'."
  }
}

variable "output_prefix" {
  description = "S3 object-key prefix used for transcoded HLS outputs."
  type        = string
  default     = "processed/"

  validation {
    condition     = length(var.output_prefix) > 0 && endswith(var.output_prefix, "/")
    error_message = "output_prefix must be non-empty and end with '/'."
  }
}

variable "allowed_file_extensions" {
  description = "Case-sensitive source-video extensions accepted by the EventBridge rule. Add uppercase variants when required."
  type        = set(string)
  default     = [".mp4", ".mov", ".mxf", ".mkv"]

  validation {
    condition = length(var.allowed_file_extensions) > 0 && alltrue([
      for extension in var.allowed_file_extensions : startswith(extension, ".") && length(extension) >= 2
    ])
    error_message = "Each allowed_file_extensions value must start with a dot, for example '.mp4'."
  }
}

variable "video_profiles" {
  description = "Adaptive-bitrate HLS renditions generated by MediaConvert."
  type = list(object({
    name_modifier      = string
    width              = number
    height             = number
    max_bitrate        = number
    qvbr_quality_level = number
  }))

  default = [
    {
      name_modifier      = "_1080p"
      width              = 1920
      height             = 1080
      max_bitrate        = 8000000
      qvbr_quality_level = 8
    },
    {
      name_modifier      = "_720p"
      width              = 1280
      height             = 720
      max_bitrate        = 5000000
      qvbr_quality_level = 7
    },
    {
      name_modifier      = "_480p"
      width              = 854
      height             = 480
      max_bitrate        = 2500000
      qvbr_quality_level = 7
    }
  ]

  validation {
    condition = length(var.video_profiles) > 0 && alltrue([
      for profile in var.video_profiles :
      profile.width > 0 &&
      profile.height > 0 &&
      profile.max_bitrate >= 100000 &&
      profile.qvbr_quality_level >= 1 &&
      profile.qvbr_quality_level <= 10 &&
      startswith(profile.name_modifier, "_")
    ])
    error_message = "Each video profile must have positive dimensions, max_bitrate >= 100000, QVBR level 1-10, and a name_modifier beginning with '_'."
  }
}

variable "hls_segment_length_seconds" {
  description = "Target HLS segment and closed-GOP duration."
  type        = number
  default     = 6

  validation {
    condition     = var.hls_segment_length_seconds >= 1 && var.hls_segment_length_seconds <= 30
    error_message = "hls_segment_length_seconds must be between 1 and 30."
  }
}

variable "media_convert_concurrent_jobs" {
  description = "Optional on-demand queue concurrency. Null allows AWS to use the account quota/default."
  type        = number
  default     = null
  nullable    = true

  validation {
    condition     = var.media_convert_concurrent_jobs == null || var.media_convert_concurrent_jobs >= 1
    error_message = "media_convert_concurrent_jobs must be null or at least 1."
  }
}

variable "kms_key_arn" {
  description = "Optional existing customer-managed KMS key ARN. When null, the module creates a key."
  type        = string
  default     = null
  nullable    = true
}

variable "kms_deletion_window_in_days" {
  description = "Waiting period before deletion of a module-created KMS key."
  type        = number
  default     = 30

  validation {
    condition     = var.kms_deletion_window_in_days >= 7 && var.kms_deletion_window_in_days <= 30
    error_message = "kms_deletion_window_in_days must be between 7 and 30."
  }
}

variable "force_destroy_buckets" {
  description = "Whether Terraform may delete non-empty VOD buckets. Keep false outside disposable environments."
  type        = bool
  default     = false
}

variable "ingest_expiration_days" {
  description = "Optional number of days before source objects expire. Null retains them indefinitely."
  type        = number
  default     = null
  nullable    = true

  validation {
    condition     = var.ingest_expiration_days == null || var.ingest_expiration_days >= 1
    error_message = "ingest_expiration_days must be null or at least 1."
  }
}

variable "output_transition_days" {
  description = "Days before transcoded outputs transition to S3 Intelligent-Tiering."
  type        = number
  default     = 30

  validation {
    condition     = var.output_transition_days >= 0
    error_message = "output_transition_days must be zero or greater."
  }
}

variable "workflow_timeout_seconds" {
  description = "Maximum Step Functions execution duration."
  type        = number
  default     = 21600

  validation {
    condition     = var.workflow_timeout_seconds >= 300 && var.workflow_timeout_seconds <= 86400
    error_message = "workflow_timeout_seconds must be between 300 and 86400."
  }
}

variable "event_max_age_seconds" {
  description = "Maximum age for EventBridge delivery retries."
  type        = number
  default     = 3600

  validation {
    condition     = var.event_max_age_seconds >= 60 && var.event_max_age_seconds <= 86400
    error_message = "event_max_age_seconds must be between 60 and 86400."
  }
}

variable "event_retry_attempts" {
  description = "Maximum EventBridge target delivery attempts."
  type        = number
  default     = 24

  validation {
    condition     = var.event_retry_attempts >= 0 && var.event_retry_attempts <= 185
    error_message = "event_retry_attempts must be between 0 and 185."
  }
}

variable "log_retention_days" {
  description = "CloudWatch Logs retention for Step Functions execution logs."
  type        = number
  default     = 30
}

variable "include_execution_data" {
  description = "Whether Step Functions logs include event payloads. Disabled by default to reduce privacy exposure."
  type        = bool
  default     = false
}

variable "enable_xray" {
  description = "Enable AWS X-Ray tracing for the Step Functions state machine."
  type        = bool
  default     = true
}

variable "alarm_topic_arns" {
  description = "Optional SNS topic ARNs receiving F3 CloudWatch alarm actions."
  type        = list(string)
  default     = []
}

variable "tags" {
  description = "Additional tags applied to F3 resources."
  type        = map(string)
  default     = {}
}